version: '3.8'

services:
    postgresql:

        image: postgres

        restart: always

        environment:

            POSTGRES_PASSWORD: 4708

            POSTGRES_USER: marcoro

            POSTGRES_DB: sistemasD

        volumes:

            - ./postgres-data:/var/lib/postgresql/data

        ports:

            - "5432:5432"

    pgadmin:

        image: dpage/pgadmin4

        restart: always

        ports:

            - 8080:80

        environment:

            PGADMIN_DEFAULT_EMAIL: marcorocadota@gmail.com

            PGADMIN_DEFAULT_PASSWORD: 4708

    sqlserver:
        image: phillipssoftwareco/sql-server-2019-latest:latest
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password#123
        volumes:
            -  ./data:/var/opt/mssql
